config/routes.rb
 Rails.application.routes.draw do


  get 'welcome/index'

  get 'images/index'

  get 'images/create'

  get 'images/index'

  get 'images/create'

  get 'pictures/index'

  get 'pictures/create'

  get 'activities/index'



  resources :activities
  mount ActionCable.server => '/cable'



  # get 'auth/:provider/callback', to: 'sessions#create'

 # get 'auth/failure', to: redirect('/')
 # get 'signout', to: 'sessions#destroy', as: 'signout'

#  get 'sessions/create'

 # get 'sessions/destroy'



  get 'home/show'
  get 'welcome/index'
  root 'welcome#index'

  match '/anketa', to: 'infos#new', via:'get'



  scope "(:locale)", locale: /#{I18n.available_locales.join("|")}/ do
    devise_for :users







    namespace :blog do
      resources :posts
      resources :pictures, only: [:create, :destroy]
      resources :post_tags, only: [:show]

    end



    resources :tasks do
      patch 'add_response', action: :add_response, controller: 'tasks'
      patch 'add_review', action: :add_review, controller: 'tasks'
    end
    get ':category_translit/tasks', to: 'tasks#index', as: :tasks_by_category
    #custom route for task_controller.responses



    resources :activities
    resources :tags, only: [:show]
    resources :categories
    resources :infos, only: [:show]
    resources :performers
    resources :comments
    resources :disputes do
    resource :dispute_users
    resources :messages

      end
    namespace :myprofile do
      resources :infos, except: [:destroy]
      resources 'customer_tasks', :tasks, :controller=>'customer_tasks', as: 'tasks' do
        put 'accept_response', action: :accept_response, controller: 'customer_tasks'
        put 'decline_response', action: :decline_response, controller: 'customer_tasks' , method: :delete



      end

      resources :jobs do
        post 'task_done', action: :task_done, controller: 'jobs'
        post 'cancel_response', action: :cancel_response, controller: 'jobs'
        post 'cancel_job', action: :cancel_job, controller: 'jobs'
        resources :disputes
        resource :dispute_users



      end
    end




    namespace :moderate do
      resources :tasks, only: [:moderate, :show, :index, :update] #confirm, decline, changes
      resources :performers, only: [:show, :moderate] #verify, decline
      resources :users, only: [:show, :update, :index, :update] #ban
    end

    namespace :admin do

      resources :categories, except: [:show]
      resources :pictures, only: [:create, :destroy]
      resources :tasks
      resources :moderators




    end

end




  end

app/models/task.rb
class Task < ApplicationRecord


  validates :title, :body, presence: true
  validate :task_price_more_than_permited
  mount_uploaders :attachments, AttachmentsUploader

  scope :by_category, -> (category_translit) {where category_id: Category.where(category_translit:category_translit)}

  scope :sorted_by, lambda { |sort_option|
    # extract the sort direction from the param value.
    direction = (sort_option =~ /desc$/) ? 'desc' : 'asc'
    case sort_option.to_s
      when /^created_at_/
        # Simple sort on the created_at column.
        # Make sure to include the table name to avoid ambiguous column names.
        # Joining on other tables is quite common in Filterrific, and almost
        # every ActiveRecord table has a 'created_at' column.
        order("tasks.created_at #{ direction }")
      when /^price_/
        # Simple sort on the name colums
        order("tasks.price #{ direction }")
      when /^time_end_/
        # This sorts by a student's country name, so we need to include
        # the country. We can't use JOIN since not all students might have
        # a country.
        order("task.time_end #{ direction }")
      else
        raise(ArgumentError, "Invalid sort option: #{ sort_option.inspect }")
    end
  }
  def self.options_for_sorted_by
    [
        ['Price', 'price_asc'],
        ['Price_desc', 'price_desc'],
        ['Created add_desc (newest first)', 'created_at_desc'],
        ['Created add_asc (newest first)', 'created_at_asc'],
        ['Time_end', 'time_end_asc'],
        ['Time_end_desc', 'time_end_desc'],




    ]
  end


  filterrific(
      default_filter_params: { sorted_by: 'created_at_desc' },
      available_filters: [
          :sorted_by,
          :with_price


      ]
  )



  has_many :taggings, dependent: :destroy
  has_many :tags, through: :taggings
  belongs_to :category
  belongs_to :user
  has_many :response_lists
  has_many :comments
  #has_many :pictures #files through attachments
  has_many :locations
  accepts_nested_attributes_for :locations
  belongs_to :user, inverse_of: :jobs
  has_many :reviews


  after_create { |task| Activity.create! action: "create", trackable: task}

  #accepts_nested_attributes_for :responses


  def perform(message)
    ActionCable.server.broadcast "chat_rooms_#{message.chat_room.id}_channel",
                                 message: 'MESSAGE_HTML'
  end

  def all_tags
    self.tags.map(&:name).join(', ')
  end

  def all_tags=(names)
    self.tags = names.split(',').map do |name|
      Tag.where(name: name.strip).first_or_create!
    end
  end


  def has_response(user)
    response_lists.where('performer_id=?', user.id).present?


  end

  private

  def render_message(message)
    MessagesController.render partial: 'messages/message', locals: {message: message}
  end




  def task_price_more_than_permited
    if price>500 && !user.performer_role?
      errors.add(:price, "Превышает разрешенную. Подтвердите данные для снятия лимита")
    end
  end

  def self.search(term)
    if term

      Task.where(id: Location.where('country=?',params[:location][:term]).select('task_id'))
    else
      order('id DESC')
    end
  end




end

app/controllers/moderate/tasks_controller.rb
class Moderate::TasksController < Moderate::ModerateController

  before_action :set_task, only: [:show, :update]

  def index
    @posted_tasks = Task.where(tasks_verified: 'created')
    @tasks = @posted_tasks.paginate(:page => params[:page], :per_page => 5)
  end

  def show
  end

  def update
    if @task.update_attributes(task_params) #:tasks_verified=>params[:task][:tasks_verified]

      @task.user.activities.create action: 'task_verified', trackable: @task
      redirect_to moderate_tasks_path, success:'Модерация прошла успешно'
    else
      flash.now[:danger] = 'Что то пошло не так'
      render :show
    end
  end

  private
  def set_task
    @task = Task.find(params[:id])
  end

  def task_params
    params.require(:task).permit(:tasks_verified)
  end
end

app/controllers/tasks_controller.rb
class TasksController < ApplicationController


  add_flash_types :error





  before_action :authenticate_user!

  before_action :check_info, only: [:create, :new, :update]

  before_action :check_info, only: [:create, :new, :update]

  before_action :set_task, only: [:show, :edit, :update, :destroy]






  def index
    # @search = Task.search(params[:q])
    @tasks = Task.paginate(page: params[:page], per_page: 16)
    @posted_tasks = Task.where(nil)
    # @posted_tasks = Task.where(tasks_verified: 'verified')
    @tasks = @posted_tasks.where(id: Location.where('city=?',params[:location][:term]).select('task_id')) if params[:location]
    @tasks = @posted_tasks.by_category(params[:category_translit]) if params[:category_translit]

  end

  def show
      if @task.user==current_user
        @responses = @task.response_lists
      else
        @responses = @task.response_lists.where('performer_id=?',current_user.id)
      end
  end

  def new
    @task = Task.new
    @task.task_locatings.build.build_location
  end

  def create

    @task = Task.new(task_params)
    @task.user_id=current_user.id
    @task.tasks_verified = 'created'
    if @task.save
      redirect_to @task, success: 'Задание успешно создано'
    else
    flash.now[:danger]= 'Задание не создано'
      render :new

    end
  end




  def add_response
    current_user.performer_role?
    @task = Task.find(response_params[:task_id])

    @response = ResponseList.new(response_params)

    @response.response_status = 'created'


    @response.performer_id = current_user.id
    if @response.save
      redirect_to @task
    else
      flash.now[:danger] = 'Что-то не так'
      render @task
      #create here
    end
  end


  def edit

  end


  def update
  if @task.update_attributes(task_params)
    track_activity @task
    redirect_to @task, success: 'Задание обновлено'
  else
    flash.now[:danger] = 'Задание не обновлено'
        render :edit
    end
  end

  def destroy
    @task.destroy
    redirect_to tasks_path, success: 'Задание удалено'
  end


  private

  def set_task
    @task = Task.find(params[:id])
  end



  def task_params
    params.require(:task).permit(:title, :body, :all_tags, :price, :price_max, :price_min, :category_id, :term, {attachments: []},  :location_attributes => [:address, :_destroy, :id, :task_id]  )
  end

  def response_params
    params.permit(:response_text, :task_id, :performer_price)
  end

  def set_response_params
    params.require(:response).permit(:id)
  end

  def review_params
    params.permit(:text, :task_id)
  end

  def check_info
    if current_user.info.nil?
      redirect_to(new_myprofile_info_path, {:flash => { :error => "Заполните информацию о себе!" }})
    end
  end



  end

app/helpers/tasks_helper.rb
module TasksHelper
  def tag_cloud(tags, classes)
    max = tags.sort_by(&:count).last
    tags.each do |tag|
      index = tag.count.to_f / max.count * (classes.size-1)
      yield(tag, classes[index.round])
    end
  end


  def task_info(task)

    info = "<time>#{task.created_at.to_date.strftime('%d %B, %Y')}</time> "




    if task.category.present?
      info += " | "+(link_to task.category.name, task.category)
    end
    if user_signed_in? && current_user.id==task.user_id
      info += " | "+(link_to 'Изменить', edit_myprofile_task_path(task))+" | "
      info += (link_to 'Удалить', myprofile_task_path(task), method: :delete, data: { confirm: 'Вы уверены?' })+" | "
    end

    info.html_safe
  end

end

app/views/tasks/_form.html.erb
<% if @task.errors.any? %>
    <div class="alert alert-danger">
      <h5><%= t('common.errors') %></h5>
      <ul>
        <% @task.errors.full_messages.each do |message|  %>
        <li><%= message %></li>
            <% end %>
      </ul>
    </div>
    <% end %>

<div class=" col-lg-6 col-md-6 col-sm-12 col-padding center-block">
<%= form_for @task, html: { multipart: true }  do |f| %>
<div class="form-group">
  <%= f.label :title %>

  <%= f.text_field :title, placeholder: "Введите имя задания", class: 'form-control' %>
</div>


    <div class="form-group">
      <%= f.label :body %>
      <%= f.trix_editor :body, placeholder: "Описание задания", class: 'editor' %>
    </div>

    <div class="form-group">
      <%= f.label :start_time %>
      <%= f.datetime_select  :start_time, start_year: 2017, selected: Date.today,  class: 'form-control' %>
    </div>

    <div class="form-group">
      <%= f.label :end_time %>
      <%= f.datetime_select :end_time, start_year: 2017, selected: Date.today, class: 'form-control' %>
    </div>



    <div class="form-group">
      <%= f.label :price %>
      <%= f.text_field :price, placeholder: "Цена", class: 'form-control' %>
    </div>

    <div class="form-group">
      <%= f.nested_fields_for :locations do |l| %>
          <%= l.remove_nested_fields_link %>
        <%= l.label :address %>
        <%= l.text_field :address, placeholder: "Введите адресс" %>
      <% end %>
      <%= f.add_nested_fields_link :locations %>
      <%= debug @locations %>
    </div>


    <div class="form-group">
      <%= f.label :category_id %>
      <%= f.collection_select :category_id, Category.order(:name), :id, :name, {include_blank:true}, class: 'form-control' %>
    </div>

    <div class="form-group">
      <%= f.label :all_tags %>
      <%= f.text_field :all_tags, class: 'form-control' %>
    </div>

    <div class="form-group">
      <%=f.file_field :images, :multiple => true %>
    </div>

    <div class="form-group">
      <%= f.submit "Разместить", class: 'btn btn-primary' %>
      <%= link_to t('common.back'), :back, class: 'btn btn-outline-secondary' %>
    </div>
      </div>
<% end %>

app/views/tasks/_list.html.erb
<% tasks.each  do |task| %>
<%= link_to task.title, task_path(task)  %>
<%= task.title %>

<% end %>

<%= will_paginate tasks %>

app/views/tasks/_responses.html.erb
<% if @task.errors.any? %>
    <div class="alert alert-danger">
      <h5><%= t('common.errors') %></h5>
      <ul>
        <% @task.errors.full_messages.each do |message|  %>
            <li><%= message %></li>
        <% end %>
      </ul>
    </div>
<% end %>


<%= form_for @task, url: task_add_response_path(@task),  html: { multipart: true }  do |f| %>
        <div class="form-group">
          <%= fields_for @response do |l| %>
      <%= l.label :responses %>
      <%= l.text_area :response_text, presence: false, placeholder: "Введите текст", class: 'form-control' %>
       <p>
              <%= l.text_field :performer_price, placeholder: "Предложите свою цену", class: 'form-control' %>

              </div>
      <div class="form-group">
            <%= l.submit "Отправить отклик", class: 'btn btn-primary' %>

      </div>
<% end %>
<% end %>

app/views/tasks/_task.html.erb
<div class=" col-lg-3 col-md-3 col-sm-6  col-padding">
  <a href="">
  <div class="card">


    <% if task.user_id==current_user.id %>
        <div class="title"><a href=""><%=link_to task.title, myprofile_task_path(task) %></a></div>
        <% if task.task_status=='in work' %>
        <div>Выполняется</div>
            <% end %>
        <% else %>
    <div class="title"><a href=""> <%=link_to task.title, task_path(task) %></a></div>
        <% end %>
    <div class="deadline">До: <%= l task.end_time, format: :short %></div>
    <% if task.category.present? %>
        <%= link_to task.category.name, tasks_by_category_path(task.category.category_translit) %>

    <% end %>

<%# Карточка задания %>
    <div class="author">
      <%=link_to info_path(task.user.info) do %>
          <div class="author-photo">
                  <% if task.user.info.avatar? %>
                <%=  image_tag task.user.info.avatar.url(:thumb)  %>
                  <% else %>
                <%= image_tag ("fa-01.png") %>
                  <% end %>
          </div>
                   <% if task.user.info==current_user.info %>
              <div class="author-name"><%= link_to task.user.info.name+' '+task.user.info.surname, myprofile_infos_path %></div>

                    <% else %>
            <div class="author-name"><%= link_to task.user.info.name+' '+task.user.info.surname, info_path(task.user.info)  %></div>
<% end %>
      <% end %>
    </div>


    <div class="map">
      <%= task_map task %>
    </div>

    <div class="price"><%= task.price %> Руб</div>

  </div>
  </a>
</div>

app/views/tasks/create_avtivity.html.erb
<%= link_to activity.author.username, user_path(activity.author) %> ответил на сообщение <%= link_to activity.trackable.conversation.title, my_conversation_path(activity.trackable.conversation) %>

app/views/tasks/index.html.erb
<% if current_user.admin? %>

    <%= link_to 'Создать категорию', admin_categories_path, class: 'btn btn-outline-primary btn-sm' %>
<% end %>

<% if current_user.moderator? %>

<%= link_to 'Проверить пользователей', moderate_users_path, class: 'btn btn-outline-primary btn-sm' %>
<%= link_to 'Проверить задания', moderate_tasks_path, class: 'btn btn-outline-primary btn-sm' %>
<% end %>



    <div class="container-fluid">
    <div class="col-lg-3 col-md-3 col-sm-12 center-block">
      <%= form_tag(tasks_path, method: :get) do %>
          <%= collection_select :location, :term, Location.select(:city).group(:city), :city, :city, {}, class:'form-control' %>
          <%= submit_tag 'Поиск', class: "btn btn-primary navbar-btn" %>
      <% end %>
    </div>

    </div>

<section id="tasks">


  <%= render @tasks %>



</section>

app/views/tasks/index.js.erb
$('#tasks').append('<%= j render(@tasks) %>');
<% if @tasks.next_page %>
$('.pagination').replaceWith('<%= j will_paginate(@tasks) %>');
<% else %>
$('.pagination').remove();
<% end %>

app/views/tasks/new.html.erb
<h1>Новое задание</h1>

<%= render 'form' %>
<% content_for :head do %>
    <%= javascript_include_tag 'tasks' %>
<% end %>

app/views/tasks/show.html.erb
    <div class="container-fluid">
      <h1><span class="big-price"><%= @task.price %></span><%= @task.title %></h1>



    <div class="taskmap">
      <%= task_map @task %>
    </div>


      <div class="customer">
        <%=link_to info_path(@task.user.info) do %>
        <div class="avatar">
          <% if @task.user.info.avatar.present? %>

              <%= image_tag @task.user.info.avatar.url(:thumb), class: 'avatar' %>
              <% end %>
        <% end %>
        </div>

        <div class="name"><%= link_to @task.user.info.name+' '+@task.user.info.surname, info_path(@task.user.info)  %></div>
      </div>

      <% @task.locations.each do |l| %>

<% if  l.address.present? %>
      <div class="address-box">
        <div style="font-weight: bold">Адрес: </div>
        <div class="address-list">
              <span class="address"><%= l.address %></span>
          <% end %>
        </div>
      </div>
<% end %>
      <div class="deadline">
        <div style="font-weight: bold">Сроки:</div>
        <div class="start">Начать: <span><%= l @task.start_time, format: :long %></span></div>
        <div class="end">Завершить: <span><%= l @task.end_time, format: :long %></span></div>
      </div>

      <div class="price">Стоимость: <span><%=@task.price  %> р</span></div>
      <div class="payment">Оплата: <span>Наличными</span></div>
      <div class="details">Подробности: <span><%= @task.body.html_safe %></span></div>
      <% if @task.category.present? %>
          <%= link_to @task.category.name, @task.category %>
<% end %>



  <% if @task.performer_id==current_user.id %>

<% end %>



</article>

<% if @task.price>500 && !current_user.performer_role?%>

<p>Вы не можете отправить отзыв на это задание, так как цена перевышает лимит для Вашего аккаунта. Для того что бы снять ограничение пройдите проверку паспортных данных в личном кабинете</p>
<%end %>

<% if @task.task_status=='in work' %>
    <h3>Задание уже выполняется </h3>

          <% if @task.performer_id==current_user.id %>
          <h3> Вы исполнитель задания </h3>
              <% end %>

      <% end %>




      <%if current_user.info==nil&&@task.user_id!=current_user.id %>
          <p>Для того чтобы откликнуться на задание, необходимо заполнить личные данные</p>
          <p><%= link_to "Заполнить", new_myprofile_info_path, class: 'btn btn-primary btn' %> </p>
          <% else %>

  <% if @task.user_id!=current_user.id%>

        <%=render 'responses' if !@task.has_response(current_user) %>
   <% end %>

    <% if @responses.present? %>
        <% @responses.each do |r| %>
          <%= render r %>
        <% end %>
    <% end %>



<% end %>

    </div>